---
version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - ./config:/config
      - ./tv:/tv
      - ./movies:/movies
   # ports:
   #   - 32400:32400
    restart: unless-stopped

